source 'http://api.berkshelf.com'

cookbook 'git'
cookbook 'ntp'
cookbook 'timezone'
cookbook 'yum'
cookbook 'yum-remi', git: 'git://github.com/aiming-cookbooks/yum-remi.git'
cookbook 'yum-repoforge'
cookbook 'php'
cookbook 'apache2'
cookbook 'mysql'