source 'http://api.berkshelf.com'

# community cookbooks
cookbook 'git'
cookbook 'ntp'
cookbook 'timezone'
cookbook 'yum'
cookbook 'php'
cookbook 'php-mcrypt'
cookbook 'composer'
cookbook 'apache2'
cookbook 'database'
cookbook 'mysql'
cookbook 'tomcat'
cookbook 'hostsfile', git: 'git@github.com:customink-webops/hostsfile.git'
